### ISSUE TITLE
You should recheck the bot actions

### ISSUE THREAD

**Issue by vitorgalvao** [alanhg/alfred-workflows#391]
A bunch (all?) your workflows had automated updates recently via GitHub actions. They all received irrelevant modifications, such as adding new unnecessary icons and QR Code even got an unused Swift script and unsigned binary (which as you know, cannot be approved). But only the `.alfredworkflow` files had changes, so it seems whatever your GitHub action is doing, it may be rebuilding your workflows against old commits.

**Comment by alanhg** [comment]
> A bunch (all?) your workflows had automated updates recently via GitHub actions. They all received irrelevant modifications, such as adding new unnecessary icons and QR Code even got an unused Swift script and unsigned binary (which as you know, cannot be approved). But only the `.alfredworkflow` files had changes, so it seems whatever your GitHub action is doing, it may be rebuilding your workflows against old commits.

I will check it.

**Comment by alanhg** [comment]
1. I have already reverted the main branch to the point in time before all workflow bulk updates, to avoid affecting other services.
2. The current issue is, I want to change the CI build from being based on the workflow binary files to being based on the src source code. The advantage of this is that it makes handling community PRs more convenient. However, the problem is, every time there's a new submission, how do I ensure that only the corresponding modified directory is packaged and built? I'm unsure if this change is more reasonable. @vitorgalvao
